In [1]:
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

X = tf.Variable([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
], dtype=tf.float32)

In [2]:
X

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float32)>

In [3]:
tf.size(X)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [4]:
tf.shape(X)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3])>

In [5]:
tf.size(tf.shape(X))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [6]:
X.numpy()

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float32)

In [7]:
X[0]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [8]:
X[0,0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [9]:
X[0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>